### PR TITLE
Add flycheck support

### PR DESCRIPTION
**Pull request by fmdkdd**
I've added flycheck support, by hooking into `lsp--on-diagnostics` and adding a generic checker that transforms the `lsp-diagnostic` struct into `flycheck-error`.

I've not activated this suppor by default.  One should run:
```
 (require 'lsp-flycheck)
 (lsp-flycheck-setup)
```
beforehand.

After that, whenever `lsp-mode` gets diagnostics back from the language server, `lsp-flycheck` start `flycheck-buffer` with the collected diagnostics.

I've only tested it with the latest RLS.

### CODE REVIEW

**Comment by vibhavp** [comment]
looks good. Thanks!

**Comment by fmdkdd** [comment]
Great!  Feel free to tinker with it.

**Comment by vibhavp** [comment]
btw, wouldn't disable automatic syntax check for flycheck _everwhere_? That probably isn't desirable, so is there a way to the next timed check do nothing?

**Comment by fmdkdd** [comment]
Hmm right, I thought it was buffer-local without checking it.  You should use `setq-local` rather to set it only in the current buffer.

**Comment by vibhavp** [comment]
Alright, thanks.

**Pull request merged**
